### ISSUE TITLE
How to follow this tutorial

### ISSUE THREAD

**Issue by spcrobocar** [methylDragon/ros-sensor-fusion-tutorial#9]
I do not know how to start and follow this tutorial. Do I have to "Buy you a coffee" to start?

**Comment by methylDragon** [comment]
The tutorial is in the Markdown files, closing this issue

https://github.com/methylDragon/ros-sensor-fusion-tutorial/blob/master/01%20-%20ROS%20and%20Sensor%20Fusion%20Tutorial.md

https://github.com/methylDragon/ros-sensor-fusion-tutorial/blob/master/02%20-%20Global%20Pose%20Estimate%20Fusion%20(Example%20Implementation).md
